### ISSUE TITLE
Geforce Now

### ISSUE THREAD

**Issue by Mioni** [cmonBruuh/poescript#2]
Is it possible to run this script in Geforce Now?

**Comment by cmonBruuh** [comment]
Haven't tried.

**Comment by Mioni** [comment]
I did a test and it doesn't work, how would you fix it? I have other scripts that work but I prefer your script. 😁

**Comment by cmonBruuh** [comment]
What are you doing with Geforce Now and the script? I don't see the connection, since I don't use Geforce Now myself.

**Comment by Mioni** [comment]
I play Poe in Geforce Now.
I found another script that works, thanks.
