### ISSUE TITLE
using custom times for flask causes kick

### ISSUE THREAD

**Issue by SmartKoolAid** [cmonBruuh/poescript#3]
when i assign "2345" for flasks textbox, and then set indiviual timers in milliseconds for those flasks, I get kicked from POE for "too many actions"

**Comment by cmonBruuh** [comment]
If you set individual flask timers with the buttons 1,2,3,4 or 5 you don' have to enter anything in the flask text box, same for timer text box, leave both blank if you set the timers via the buttons
