### ISSUE TITLE
CTRL+ Skills?

### ISSUE THREAD

**Issue by SmartKoolAid** [cmonBruuh/poescript#4]
Is there any way to provide the same functionality of the Q, W,E,R,T buttons but for the skills on the ctrl+ tab?

for example i have some skills i want to use spacebar with or ctrl+t

**Comment by cmonBruuh** [comment]
Give me an example of a skill which you put in the ctrl tab

**Comment by SmartKoolAid** [comment]
So right now I have
Q- Toxic Rain(manual)
W- Withering Step(manual)
E- Dash (manual)
R-Immortal Call(auto every second)
T-Blood Rage(Every 20 seconds)
Space - (Vaal haste) <- This one i would like to have.

I supposed its not really necessary, but I think it would be a cool feature for like the button below "HK" to be a "var" macro allowing you to select the hotkey you want to set it to, and the timer.

**Comment by cmonBruuh** [comment]
Will see if I'll implement something like this.
This is a CR and not an issue thus I'll close it.
