### ISSUE TITLE
State issue?

### ISSUE THREAD

**Issue by V4mpyr** [cmonBruuh/poescript#5]
Hey, 

So I've read back to front the documentation on how to use your script. I have  12345 in the flask box, timer set to 4000. Regards of pressing f2 it will not change the game state from "sleeping". I managed to get it to work but it's inconsistent. Resolution of screen is  1920 x1080 in full screen mode. I noticed it will not work at all in windowed mode.

**Comment by cmonBruuh** [comment]
It's only possible to run the script while poe is the active window. So f.ex. if you're at your browser and you click F2 - it won't activate. This means that "state" only changes when your poe window is the active window.

**Comment by V4mpyr** [comment]
This is what I gathered was the intended function however this is not working as intended for me.

I've have only the script and POE running. I load the script. I put 12345  to run all flasks, i set 4000 for timer. Load game up, and hit F2 and nothing happens.

I alt tab, close out of the script and reload it. If I don't put 12345 and the timer and just hit f2 while in game, it will show "blocked" on both fields.. once I put in the flasks I want to use and the timer it does nothing. I hit F3 to reset it, then f2 again... still nothing. 

I am happy to take a video of my steps so you can see it. I'll post a link in a min

**Comment by V4mpyr** [comment]
https://ufile.io/gfrlxrq8

**Comment by cmonBruuh** [comment]
Ok thanks for your video. Please try another Hotkey then. You can set one up with the HK button or run Hotkeys.ahk
Just try a random letter or number which is not already used by another function.
I don't know much about laptops but it may has issues with the "FN" button on the bottom left corner on your keyboard. This button may be activated and if you click F2 it doesn't really click F2 but it executes the F2 function on your system. (f.ex. brightness, volume or something else)
I tested windowed mode really quick. That is not the problem as it worked for me.
